### ISSUE TITLE
Is the test_data.csv real data?

### ISSUE THREAD

**Issue by Beyyes** [fooSynaptic/py_pcalg#1]
I wonder the meaning of test_data.csv, is it the real data?

**Comment by fooSynaptic** [comment]
> I wonder the meaning of test_data.csv, is it the real data?

yes, it's the real data, you can see the demo from https://github.com/fooSynaptic/py_pcalg/blob/master/demo/WechatIMG7.png

i preprocessed the data with R software so they loss the variable name, but you can see the result from the demo graph, which sina sport and peking date(day-month) are strongly directed.
(I remember the vector of tokens are generated with `word2vec`)

**Comment by Beyyes** [comment]
So the first line of test_data ```"","sport","X0","X0.1","X9","X0.000936521","X0.010105104","X0.056403412","X0.056197389","X0.96","X0.100","X0.175","X0.189"``` is just headline?

And I think the picture in https://github.com/fooSynaptic/py_pcalg/blob/master/demo/WechatIMG7.png and running result 
![image](https://user-images.githubusercontent.com/6756545/62200562-45540780-b3b8-11e9-9e5b-7c943024c1f5.png) is not similar, the running result has more edges between nodes, so how to explain the running result?

Thanks.

**Comment by fooSynaptic** [comment]
Yes you find out this problem, the demo graph was generated with R package pcalg, quiet different with the rep's result.
That's embarrassing but the truth is i havn't review my code after i finish it. 
In my opinion, most of the casual features are computed(refer to the R package result), but the **code of independent test** part lost some feature compare to the raw R function(i deleted some lines for they are hard to realization in python, i admitted), **so more dependent edge are generated**, which lead to this confusing result.
If i have time, i will review the code, thank you.
